/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EmployeeId = IDL.Nat;
export const Region = IDL.Text;
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'penyuluh' : IDL.Null });
export const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Employee = IDL.Record({
  'id' : EmployeeId,
  'nip' : IDL.Text,
  'region' : Region,
  'status' : Status,
  'birthDate' : IDL.Int,
  'createdAt' : IDL.Int,
  'role' : Role,
  'fullName' : IDL.Text,
  'birthPlace' : IDL.Text,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'gender' : Gender,
  'phone' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'position' : IDL.Text,
});
export const WorkTargetId = IDL.Nat;
export const WorkRealizationId = IDL.Nat;
export const WorkTarget = IDL.Record({
  'id' : WorkTargetId,
  'activityType' : IDL.Text,
  'period' : IDL.Text,
  'createdAt' : IDL.Int,
  'unit' : IDL.Text,
  'employeeId' : EmployeeId,
  'indicator' : IDL.Text,
  'targetValue' : IDL.Float64,
});
export const AuditLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'userId' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const WorkRating = IDL.Variant({
  'baik' : IDL.Null,
  'cukup' : IDL.Null,
  'kurang' : IDL.Null,
});
export const WorkRealization = IDL.Record({
  'id' : WorkRealizationId,
  'achievementPercent' : IDL.Float64,
  'evaluatedAt' : IDL.Int,
  'supervisorNotes' : IDL.Text,
  'employeeId' : EmployeeId,
  'rating' : WorkRating,
  'targetId' : WorkTargetId,
  'realizedValue' : IDL.Float64,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEmployee' : IDL.Func([Employee], [EmployeeId], []),
  'createWorkRealization' : IDL.Func(
      [WorkTargetId, EmployeeId, IDL.Float64, IDL.Text],
      [WorkRealizationId],
      [],
    ),
  'createWorkTarget' : IDL.Func([WorkTarget], [WorkTargetId], []),
  'deleteEmployee' : IDL.Func([EmployeeId], [], []),
  'deleteWorkRealization' : IDL.Func([WorkRealizationId], [], []),
  'deleteWorkTarget' : IDL.Func([WorkTargetId], [], []),
  'getAllAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllWorkRealizations' : IDL.Func(
      [],
      [IDL.Vec(WorkRealization)],
      ['query'],
    ),
  'getAllWorkTargets' : IDL.Func([], [IDL.Vec(WorkTarget)], ['query']),
  'getAuditLogsByUserId' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AuditLog)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployee' : IDL.Func([EmployeeId], [Employee], ['query']),
  'getEmployeesByPosition' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Employee)],
      ['query'],
    ),
  'getEmployeesByRegion' : IDL.Func([Region], [IDL.Vec(Employee)], ['query']),
  'getWorkRealizationsByEmployeeId' : IDL.Func(
      [EmployeeId],
      [IDL.Vec(WorkRealization)],
      ['query'],
    ),
  'getWorkRealizationsByRating' : IDL.Func(
      [WorkRating],
      [IDL.Vec(WorkRealization)],
      ['query'],
    ),
  'getWorkRealizationsByTargetId' : IDL.Func(
      [WorkTargetId],
      [IDL.Vec(WorkRealization)],
      ['query'],
    ),
  'getWorkTargetsByEmployeeId' : IDL.Func(
      [EmployeeId],
      [IDL.Vec(WorkTarget)],
      ['query'],
    ),
  'getWorkTargetsByPeriod' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkTarget)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateEmployee' : IDL.Func([EmployeeId, Employee], [], []),
  'updateWorkRealization' : IDL.Func(
      [WorkRealizationId, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'updateWorkTarget' : IDL.Func([WorkTargetId, WorkTarget], [], []),
  'uploadEmployeePhoto' : IDL.Func([EmployeeId, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EmployeeId = IDL.Nat;
  const Region = IDL.Text;
  const Status = IDL.Variant({ 'active' : IDL.Null, 'inactive' : IDL.Null });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'penyuluh' : IDL.Null });
  const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Employee = IDL.Record({
    'id' : EmployeeId,
    'nip' : IDL.Text,
    'region' : Region,
    'status' : Status,
    'birthDate' : IDL.Int,
    'createdAt' : IDL.Int,
    'role' : Role,
    'fullName' : IDL.Text,
    'birthPlace' : IDL.Text,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'gender' : Gender,
    'phone' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'position' : IDL.Text,
  });
  const WorkTargetId = IDL.Nat;
  const WorkRealizationId = IDL.Nat;
  const WorkTarget = IDL.Record({
    'id' : WorkTargetId,
    'activityType' : IDL.Text,
    'period' : IDL.Text,
    'createdAt' : IDL.Int,
    'unit' : IDL.Text,
    'employeeId' : EmployeeId,
    'indicator' : IDL.Text,
    'targetValue' : IDL.Float64,
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'userId' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const WorkRating = IDL.Variant({
    'baik' : IDL.Null,
    'cukup' : IDL.Null,
    'kurang' : IDL.Null,
  });
  const WorkRealization = IDL.Record({
    'id' : WorkRealizationId,
    'achievementPercent' : IDL.Float64,
    'evaluatedAt' : IDL.Int,
    'supervisorNotes' : IDL.Text,
    'employeeId' : EmployeeId,
    'rating' : WorkRating,
    'targetId' : WorkTargetId,
    'realizedValue' : IDL.Float64,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEmployee' : IDL.Func([Employee], [EmployeeId], []),
    'createWorkRealization' : IDL.Func(
        [WorkTargetId, EmployeeId, IDL.Float64, IDL.Text],
        [WorkRealizationId],
        [],
      ),
    'createWorkTarget' : IDL.Func([WorkTarget], [WorkTargetId], []),
    'deleteEmployee' : IDL.Func([EmployeeId], [], []),
    'deleteWorkRealization' : IDL.Func([WorkRealizationId], [], []),
    'deleteWorkTarget' : IDL.Func([WorkTargetId], [], []),
    'getAllAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllWorkRealizations' : IDL.Func(
        [],
        [IDL.Vec(WorkRealization)],
        ['query'],
      ),
    'getAllWorkTargets' : IDL.Func([], [IDL.Vec(WorkTarget)], ['query']),
    'getAuditLogsByUserId' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AuditLog)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployee' : IDL.Func([EmployeeId], [Employee], ['query']),
    'getEmployeesByPosition' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Employee)],
        ['query'],
      ),
    'getEmployeesByRegion' : IDL.Func([Region], [IDL.Vec(Employee)], ['query']),
    'getWorkRealizationsByEmployeeId' : IDL.Func(
        [EmployeeId],
        [IDL.Vec(WorkRealization)],
        ['query'],
      ),
    'getWorkRealizationsByRating' : IDL.Func(
        [WorkRating],
        [IDL.Vec(WorkRealization)],
        ['query'],
      ),
    'getWorkRealizationsByTargetId' : IDL.Func(
        [WorkTargetId],
        [IDL.Vec(WorkRealization)],
        ['query'],
      ),
    'getWorkTargetsByEmployeeId' : IDL.Func(
        [EmployeeId],
        [IDL.Vec(WorkTarget)],
        ['query'],
      ),
    'getWorkTargetsByPeriod' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkTarget)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateEmployee' : IDL.Func([EmployeeId, Employee], [], []),
    'updateWorkRealization' : IDL.Func(
        [WorkRealizationId, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'updateWorkTarget' : IDL.Func([WorkTargetId, WorkTarget], [], []),
    'uploadEmployeePhoto' : IDL.Func([EmployeeId, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };