/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AuditLog {
  'id' : bigint,
  'action' : string,
  'userId' : Principal,
  'description' : string,
  'timestamp' : bigint,
}
export interface Employee {
  'id' : EmployeeId,
  'nip' : string,
  'region' : Region,
  'status' : Status,
  'birthDate' : bigint,
  'createdAt' : bigint,
  'role' : Role,
  'fullName' : string,
  'birthPlace' : string,
  'email' : string,
  'updatedAt' : bigint,
  'gender' : Gender,
  'phone' : string,
  'photo' : [] | [ExternalBlob],
  'position' : string,
}
export type EmployeeId = bigint;
export type ExternalBlob = Uint8Array;
export type Gender = { 'female' : null } |
  { 'male' : null };
export type Region = string;
export type Role = { 'admin' : null } |
  { 'penyuluh' : null };
export type Status = { 'active' : null } |
  { 'inactive' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WorkRating = { 'baik' : null } |
  { 'cukup' : null } |
  { 'kurang' : null };
export interface WorkRealization {
  'id' : WorkRealizationId,
  'achievementPercent' : number,
  'evaluatedAt' : bigint,
  'supervisorNotes' : string,
  'employeeId' : EmployeeId,
  'rating' : WorkRating,
  'targetId' : WorkTargetId,
  'realizedValue' : number,
}
export type WorkRealizationId = bigint;
export interface WorkTarget {
  'id' : WorkTargetId,
  'activityType' : string,
  'period' : string,
  'createdAt' : bigint,
  'unit' : string,
  'employeeId' : EmployeeId,
  'indicator' : string,
  'targetValue' : number,
}
export type WorkTargetId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEmployee' : ActorMethod<[Employee], EmployeeId>,
  'createWorkRealization' : ActorMethod<
    [WorkTargetId, EmployeeId, number, string],
    WorkRealizationId
  >,
  'createWorkTarget' : ActorMethod<[WorkTarget], WorkTargetId>,
  'deleteEmployee' : ActorMethod<[EmployeeId], undefined>,
  'deleteWorkRealization' : ActorMethod<[WorkRealizationId], undefined>,
  'deleteWorkTarget' : ActorMethod<[WorkTargetId], undefined>,
  'getAllAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllWorkRealizations' : ActorMethod<[], Array<WorkRealization>>,
  'getAllWorkTargets' : ActorMethod<[], Array<WorkTarget>>,
  'getAuditLogsByUserId' : ActorMethod<[Principal], Array<AuditLog>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployee' : ActorMethod<[EmployeeId], Employee>,
  'getEmployeesByPosition' : ActorMethod<[string], Array<Employee>>,
  'getEmployeesByRegion' : ActorMethod<[Region], Array<Employee>>,
  'getWorkRealizationsByEmployeeId' : ActorMethod<
    [EmployeeId],
    Array<WorkRealization>
  >,
  'getWorkRealizationsByRating' : ActorMethod<
    [WorkRating],
    Array<WorkRealization>
  >,
  'getWorkRealizationsByTargetId' : ActorMethod<
    [WorkTargetId],
    Array<WorkRealization>
  >,
  'getWorkTargetsByEmployeeId' : ActorMethod<[EmployeeId], Array<WorkTarget>>,
  'getWorkTargetsByPeriod' : ActorMethod<[string], Array<WorkTarget>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateEmployee' : ActorMethod<[EmployeeId, Employee], undefined>,
  'updateWorkRealization' : ActorMethod<
    [WorkRealizationId, number, string],
    undefined
  >,
  'updateWorkTarget' : ActorMethod<[WorkTargetId, WorkTarget], undefined>,
  'uploadEmployeePhoto' : ActorMethod<[EmployeeId, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];